name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build project
      run: mkdir build && cd build && cmake . && cmake --build .

    #- name: Run tests
    #  run: |
    #    ./test-library.out