@startuml classeDiagramme
'https://plantuml.com/deployment-diagram
title <size:20><U+1F916> <color:#darkblue><u>Diagramme de classe Jeu IA</u></color><U+1F916></size>

package IA_MINMAX
{
    struct TreeNode
    {
      + TreeNode: parent
      + TreeNode[]: childs
      ---
      + Position: positionBoard      
    }

    struct Position
    {
      char: xPos
      char: yPos
    }


    TreeNode o-- Position
}

@enduml