name: Build

on:
  push:
  pull_request:
  merge_group:

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-13, macOS-latest, windows-latest]
        include:
        - os: ubuntu-latest
          cmake-init-env: CXXFLAGS=-Werror
          package-file: "*-Linux.tar.gz"
          package-name: linux_x86_64
        - os: macOS-13
          cmake-init-env: CXXFLAGS=-Werror
          package-file: "*-Darwin.tar.gz"
          package-name: macOS_x86_64
        - os: macOS-latest
          cmake-init-env: CXXFLAGS=-Werror
          package-file: "*-Darwin.tar.gz"
          package-name: macOS_arm64
        - os: windows-latest
          cmake-args: -A x64
          cmake-init-env: CXXFLAGS=/WX LDFLAGS=/WX
          package-file: "*-win64.exe"
          package-name: windows_x86_64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config cmake cmake libglew-dev xorg-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libcurl4-openssl-dev build-essential libglfw3

    - name: Prepare macOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update || true
        brew install pkg-config cmake || true
        sudo rm -rf /Library/Developer/CommandLineTools

    - name: Build in debug mode
      run: |
        mkdir debug
        cd debug
        ${{ matrix.cmake-path }}cmake -E env ${{ matrix.cmake-init-env }} ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_SYSTEM_VERSION=10.0.26100.0 -Werror=dev ..
        ${{ matrix.cmake-path }}cmake --build . --config Debug ${{ matrix.build-args }}

    - name: Build in release mode
      run: |
        mkdir release
        cd release
        ${{ matrix.cmake-path }}cmake -E env ${{ matrix.cmake-init-env }} ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release -Werror=dev ..
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }}